name: doctor_consultation
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  custom_rating_bar: ^3.0.0
  molten_navigationbar_flutter: ^1.0.1
  table_calendar: ^3.1.2
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/main-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "asset/main-logo.png"
    background_color: "#ccc"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "asset/main-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "asset/main-logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/main-logo.png
    - asset/onboarding01.jpg
    - asset/onboarding02.jpg
    - asset/onboarding03.jpg
    - asset/home-screen-profile.jpeg
    - asset/home-screen-live01.jpeg
    - asset/home-screen-live02.jpeg
    - asset/home-screen-live03.jpeg
    - asset/Home-Screen/exercise.png
    - asset/Home-Screen/eye.png
    - asset/Home-Screen/heart.png
    - asset/Home-Screen/tooth.png
    - asset/Home-Screen/dr-grab.jpeg
    - asset/Home-Screen/dr-blessing.jpeg
    - asset/Home-Screen/feature-dr-1.jpeg
    - asset/Home-Screen/feature-dr-2.jpeg
    - asset/Home-Screen/feature-dr-3.jpeg
    - asset/Live-Screen/dr.jpeg
    - asset/Live-Screen/first.jpeg
    - asset/Live-Screen/second.jpeg
    - asset/Live-Screen/third.jpeg
    - asset/Live-Screen/fourth.jpeg
    - asset/Find-Doctors/one.jpeg
    - asset/Find-Doctors/two.jpeg
    - asset/Find-Doctors/three.jpeg
    - asset/Find-Doctors/four.jpeg
    - asset/Popular-Doctors/one.jpeg
    - asset/Popular-Doctors/two.jpeg
    - asset/Popular-Doctors/three.jpeg
    - asset/Popular-Doctors/one-2.jpeg
    - asset/Popular-Doctors/three-2.jpeg
    - asset/map.png
    - asset/Appointment/1.png
    - asset/Appointment/2.png
    - asset/Appointment/3.png
    - asset/Appointment/4.png
    - asset/calender.png
    - asset/abuzar.jpeg
    - asset/cancel.png
    - asset/Hassam/doctor.png
    - asset/Hassam/home.png
    - asset/Hassam/profile.png
    - asset/Hassam/reports.png
    - asset/Hassam/1.jpeg
    - asset/Hassam/2.jpeg
    - asset/Hassam/3.jpeg
    - asset/Hassam/Group1.png
    - asset/Hassam/hasso.jpg
    - asset/Hassam/headline.png
    - asset/Hassam/illustration.png
    - asset/Hassam/illustration1.png
    - asset/Hassam/step.png
    - asset/assets/Find-Doctors/doctor_one.png
    - asset/assets/Find-Doctors/doctor_two.png
    - asset/assets/Find-Doctors/doctor_three.png
    - asset/assets/Find-Doctors/doctor_four.png
    - asset/assets/image/image_1.png
    - asset/assets/image/image_2.png
    - asset/assets/image/image_3.png
    - asset/assets/image/mypic.jpg
    - asset/assets/image/child.webp
    - asset/assets/order-managment/one-removebg-preview.png
    - asset/assets/order-managment/two-removebg-preview.png
    - asset/assets/order-managment/three-removebg-preview.png
    - asset/assets/order-managment/four-removebg-preview.png
    - asset/assets/order-managment/five-removebg-preview.png
    - asset/assets/order-managment/six-removebg-preview.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
